
export const Routers = {
    /// ----------- Website ------------- ////
    WEBSITE: "/",
    /// ----------- User panel ------------- ////
    UNIVERSAL: "*",
    REGISTER: "/register",
    LOGIN: "/login",
    DASHBOARD: "/",
    ADD_WITHDRAWAL: "/add-withdrawal",
    ADD_TOPUP: "/add-topup",
    CLOUD_MINING: "/cloud-mining",
    TOPUP_HISTORY: "/topup-history",
    WITHDRAWAL_HISTORY: "/withdrawal-history",
    RAISE_TICKET: "/raise-ticket",
    RAISE_TICKET_LIST: "/raise-ticket-list",
    TRADING_INCOME_HISTORY: "/trading-income-history",
    DIRECT_REFERRAL_INCOME: "/direct-referral-income-history",
    GENERATION_INCOME: "/level-income-history",
    DAILY_INCOME: "/daily-income-history",
    GLOBAL_INCOME_HISTORY: "/global-income-history",
    MATCHING_INCOME_HISTORY: "/matching-income-history",
    RANK_LEADER_BOARD: "/rank-leader-board",
    PROFILE: "/profile",
    OUR_PLANS: "/all-plan",
    DIRECT_REFERRALS: "/direct-referrals",
    INVESTMENT_REPORTS: "/purchase-plan-reports",
    AI_TRADE:"/ai-trade",
    AI_TRADE_HISTORY:"/ai-trade-reports",
    TEAM_PERFORMANCE:"/team-performance-history",
    
    /// ----------- Admin panel ------------- ////
    ADMIN_LOGIN: "/admin/login",
    ADMIN_DASHBOARD: "/",
    ADD_BANNER: "/add-banner",
    ALL_USER_LIST: "/all-user",
    BANNER_LIST: "/all-banner",
    UPDATE_BANNER: "/update-banner",
    WITHDRAWAL_HISTORY: "/withdrawal-history",
    RAISE_TICKET_LIST: "/raise-ticket-list",
    INVESTMENT_INCOME: "/investment-history",
    DAILY_ROI_INCOME: "/daily-income-history",
    SELF_INCOME: "/level-income-history",
    MATCHING_INCOME: "/matching-income-history",
    TRADING_INCOME: "/trading-profit-history",
    GLOBAL_INCOME: "/global-achiever-history",
    RANK_INCOME: "/rank-reward-history",
    REFERRAL_INCOME: "/referral-history",
    ENQUIRY_HISTORY: "/enquiry-history",
    CLOUD_MINING_HISTORY: "/cloud-mining-history",
    LIVE_ACCOUNT_INVESTMENT : "/live-account-investment",
    TEAM_PERFORMANCE_BONUS:"/team-performance-bouns",
    AI_TRADE_REPORTS:"/ai-trade-history",
    
};
