export const AllPlansContent = [
  {
    planName: "Basic",
    minPrice: "50",
    maxPrice: "1000",
    duration: "1 Month",
    commission: "8% monthly",
    descriptionEnumList: ["8% Commission monthly", "24/7 Access"],
    notIncludedBenefits: ["No Free Trial"],
    popular: false,
  },
  {
    planName: "Standard",
    minPrice: "1010",
    maxPrice: "5000",
    duration: "3 Months",
    commission: "10% monthly",
    descriptionEnumList: ["10% Commission monthly", "24/7 Access"],
    notIncludedBenefits: ["No Free Trial"],
    discount: "42%",
    popular: false,
  },
  {
    planName: "Premium",
    minPrice: "5100",
    maxPrice: "Above 5100",
    duration: "6 Months",
    commission: "12% monthly",
    descriptionEnumList: ["12% Commission monthly", "24/7 Access"],
    notIncludedBenefits: ["No Free Trial"],
    discount: "59%",
    popular: true,
  },
  {
    planName: "Live A/C",
    minPrice: "1000",
    maxPrice: "Above 1000",
    duration: "6 Months",
    commission: "40% On Trade",
    descriptionEnumList: ["40% On Trade Profit Invest", "24/7 Access"],
    notIncludedBenefits: ["No Free Trial"],
    discount: "59%",
    popular: true,
  },
];
